### ISSUE TITLE
u_fact = fact_graph_choose @ atten_tensor

### ISSUE THREAD

**Issue by Elaine10-27** [prometheusXN/LADAN#1]
Can you explain the u_fact = fact_graph_choose @ atten_tensor statement? I noticed that this statement appeared in many running files. But there was an error in this line when running. Thanks ~

**Comment by prometheusXN** [comment]
The u_fact = fact_graph_choose @ atten_tensor  is used to choose the attention vector of the corresponding law article group to compute the representation of fact description in re-encoder.
In fact, the fact_graph_choose is got by:
fact_graph_choose = tf.where(fact_graph_choose == tf.reduce_max(fact_graph_choose, -1), tf.ones_like(fact_graph_choose), tf.zeros_like(fact_graph_choose))
, where only the position of the maximum value is one, the other position is zero.
Then, we use the inner product operation to pick the corresponding attention vector in atten_tensor.

I hope this answer can help you!


xunuo0109@hotmail.com
 
From: elaine
Date: 2020-04-26 19:49
To: prometheusXN/LADAN
CC: Subscribed
Subject: [prometheusXN/LADAN] u_fact = fact_graph_choose @ atten_tensor (#1)
Can you explain the u_fact = fact_graph_choose @ atten_tensor statement? I noticed that this song sentence appeared in many running files. But there was an error in this line when running. Thanks ~

**Comment by Elaine10-27** [comment]
Thank you for your patience and prompt response. I have another question about dataset. I processed the data according to tongji.py. But the training data and test data screened out are less than those described in the paper. I don't know which step is the problem. I directly use the new_law.txt and new_accu.txt given in your code as clearlawlist and cleararaculist. Looking forward to your reply ~

**Comment by prometheusXN** [comment]
Our dataset is from Wenmian Yang who is the author of paper "Legal Judgment Prediction via Multi-Perspective Bi-Feedback Network" (IJCAI 2019).
There is actually some difference compared with the preliminary dataset of CAIL.
Can you give me an e-mail address? I'll send the CAILsmall dataset to you.



xunuo0109@hotmail.com
 
From: elaine
Date: 2020-04-28 15:48
To: prometheusXN/LADAN
CC: prometheusXN; Comment
Subject: Re: [prometheusXN/LADAN] u_fact = fact_graph_choose @ atten_tensor (#1)
Thank you for your patience and prompt response. I have another question about dataset. I processed the data according to tongji.py. But the training data and test data screened out are less than those described in the paper. I don't know which step is the problem. I directly use the new_law.txt and new_accu.txt given in your code as clearlawlist and cleararaculist. Looking forward to your reply ~

**Comment by Elaine10-27** [comment]
Thank you so much. This is my mail box <elaine1027zhl@hotmail.com>. Looking forward to your mail. Thanks ~

**Comment by prometheusXN** [comment]
Ok, I have sent the dataset to you, please check it~~

**Comment by Elaine10-27** [comment]
I have received it.   # ^_^ #
