### ISSUE TITLE
法条预测任务

### ISSUE THREAD

**Issue by ruarua6666** [prometheusXN/LADAN#13]
我想请问下，在这篇论文中，是把法条预测当成单标签多分类任务去做了吗？

**Comment by prometheusXN** [comment]
是的，JLP任务最开始的时候都是作为单标签多分类的任务来处理的，你可以参考这边论文一些其他的引用文献。



***@***.***
 
发件人： ruarua6666
发送时间： 2023-04-25 22:09
收件人： prometheusXN/LADAN
抄送： Subscribed
主题： [prometheusXN/LADAN] 法条预测任务 (Issue #13)
我想请问下，在这篇论文中，是把法条预测当成单标签多分类任务去做了吗？
