### ISSUE TITLE
数据预处理问题

### ISSUE THREAD

**Issue by Yyy11181** [prometheusXN/LADAN#14]
import json
import thulac
import re

Cutter = thulac.thulac(seg_only = True)

flaw = open("./law.txt",'r')
totallaw = 0
law2num = {}
num2law = {}

for line in flaw.readlines():
    law2num[line.strip()] = totallaw
    num2law[totallaw] = line.strip()
    totallaw += 1
print(totallaw)

flaw = open("accu.txt",'r',encoding='utf-8')
totalaccu = 0
accu2num = {}
num2accu= {}
for line in flaw.readlines():
    accu2num[line.strip()] = totalaccu
    num2accu[totalaccu] = line.strip()
    totalaccu += 1
print(totalaccu)

file1 = open("data_train.json",'r',encoding='utf-8')
file2 = open("data_test.json",'r',encoding='utf-8')
file3 = open("data_valid.json",'r',encoding='utf-8')

strpass = '二审'
totalsample = 0
totlaw = [0] * totallaw
totaccu = [0] * totalaccu

for line in file1.readlines():
    dic = json.loads(line)
    if (strpass in dic["fact"] != -1 or
        len(dic["meta"]["accusation"]) > 1 or len(dic["meta"]["relevant_articles"]) > 1):
        pass
    else:
        templaw = str(dic["meta"]["relevant_articles"][0])
        tempaccu = dic["meta"]["accusation"][0]
        totlaw[law2num[templaw]] += 1
        totaccu[accu2num[tempaccu]] += 1
        totalsample += 1

for line in file3.readlines():
    dic = json.loads(line)
    if (strpass in dic["fact"] != -1 or
        len(dic["meta"]["accusation"]) > 1 or len(dic["meta"]["relevant_articles"]) > 1):
        pass
    else:
        templaw = str(dic["meta"]["relevant_articles"][0])
        tempaccu = dic["meta"]["accusation"][0]
        totlaw[law2num[templaw]] += 1
        totaccu[accu2num[tempaccu]] += 1
        totalsample += 1

print (totalsample)
clearlaw  = 0
clearaccu = 0
clearlawlist = []
clearacculist = []
clearlaw2num = {}
clearaccu2num = {}

lawfile = open("./new_law.txt", "w")
accufile = open("./new_accu.txt", "w")

for i in range(totallaw):
    if (totlaw[i] >= 100):
        clearlawlist.append(i)
        clearlaw2num[str(num2law[i])] = clearlaw
        clearlaw += 1
        lawfile.write(num2law[i] + '\n')
for i in range(totalaccu):
    if (totaccu[i] >= 100):
        clearacculist.append(i)
        clearaccu2num[num2accu[i]] = clearaccu
        clearaccu += 1
        accufile.write(num2accu[i] + '\n')

print (clearlaw, clearaccu)
print(clearlaw2num)

file1.close()
file2.close()
file3.close()
你好 这段对所有的数据统计出所有的罪名和法条的频率的代码，之后再进行过滤罪名和法条的代码，为什么没有对file2里面的数据进行统计？？

**Comment by prometheusXN** [comment]
因为你处理数据的时候不能假设你连测试集的样本都已经见过标签了


***@***.***
 
发件人： Yaoyu
发送时间： 2023-07-23 10:31
收件人： prometheusXN/LADAN
抄送： Subscribed
主题： [prometheusXN/LADAN] 数据预处理问题 (Issue #14)
import json
import thulac
import re
Cutter = thulac.thulac(seg_only = True)
flaw = open("./law.txt",'r')
totallaw = 0
law2num = {}
num2law = {}
for line in flaw.readlines():
law2num[line.strip()] = totallaw
num2law[totallaw] = line.strip()
totallaw += 1
print(totallaw)
flaw = open("accu.txt",'r',encoding='utf-8')
totalaccu = 0
accu2num = {}
num2accu= {}
for line in flaw.readlines():
accu2num[line.strip()] = totalaccu
num2accu[totalaccu] = line.strip()
totalaccu += 1
print(totalaccu)
file1 = open("data_train.json",'r',encoding='utf-8')
file2 = open("data_test.json",'r',encoding='utf-8')
file3 = open("data_valid.json",'r',encoding='utf-8')
strpass = '二审'
totalsample = 0
totlaw = [0] * totallaw
totaccu = [0] * totalaccu
for line in file1.readlines():
dic = json.loads(line)
if (strpass in dic["fact"] != -1 or
len(dic["meta"]["accusation"]) > 1 or len(dic["meta"]["relevant_articles"]) > 1):
pass
else:
templaw = str(dic["meta"]["relevant_articles"][0])
tempaccu = dic["meta"]["accusation"][0]
totlaw[law2num[templaw]] += 1
totaccu[accu2num[tempaccu]] += 1
totalsample += 1
for line in file3.readlines():
dic = json.loads(line)
if (strpass in dic["fact"] != -1 or
len(dic["meta"]["accusation"]) > 1 or len(dic["meta"]["relevant_articles"]) > 1):
pass
else:
templaw = str(dic["meta"]["relevant_articles"][0])
tempaccu = dic["meta"]["accusation"][0]
totlaw[law2num[templaw]] += 1
totaccu[accu2num[tempaccu]] += 1
totalsample += 1
print (totalsample)
clearlaw = 0
clearaccu = 0
clearlawlist = []
clearacculist = []
clearlaw2num = {}
clearaccu2num = {}
lawfile = open("./new_law.txt", "w")
accufile = open("./new_accu.txt", "w")
for i in range(totallaw):
if (totlaw[i] >= 100):
clearlawlist.append(i)
clearlaw2num[str(num2law[i])] = clearlaw
clearlaw += 1
lawfile.write(num2law[i] + '\n')
for i in range(totalaccu):
if (totaccu[i] >= 100):
clearacculist.append(i)
clearaccu2num[num2accu[i]] = clearaccu
clearaccu += 1
accufile.write(num2accu[i] + '\n')
print (clearlaw, clearaccu)
print(clearlaw2num)
file1.close()
file2.close()
file3.close()
你好 这段对所有的数据统计出所有的罪名和法条的频率的代码，之后再进行过滤罪名和法条的代码，为什么没有对file2里面的数据进行统计？？

**Comment by Yyy11181** [comment]
但是 在后面进行处理数据的时候，还是把test的数据进行处理了呀。

**Comment by Yyy11181** [comment]
这段代码不是需要统计所有数据里面对应的罪名和法条频率吗？形成一个新的crime2id 和law2id，之后再用这个对三个数据文件train,valid,test 的数据分别进行处理

**Comment by prometheusXN** [comment]
是的，这里只统计了训练集和验证集，你也可以对三个部分都进行统计，但是你的模型训练的时候实际上只见过训练集的数据，所以这里的10case per label，最好是对于训练集进行统计的，否则你的模型很可能面临few-shot或者zero-shot 的问题




***@***.***
 
发件人： Yaoyu
发送时间： 2023-07-23 17:08
收件人： prometheusXN/LADAN
抄送： prometheusXN; Comment
主题： Re: [prometheusXN/LADAN] 数据预处理问题 (Issue #14)
这段代码不是需要统计所有数据里面对应的罪名和法条频率吗？形成一个新的crime2id 和law2id，之后再用这个对三个数据文件train,valid,test 的数据分别进行处理

**Comment by Yyy11181** [comment]
10case per label？？不是过滤掉低于100次频率的法条和罪名吗？

**Comment by Yyy11181** [comment]
对了 还有一个问题，在过滤掉指定的一些低频数据之后，没有必要再划分数据集吗？还是出于哪些考虑呢？希望得到您的回答

**Comment by prometheusXN** [comment]
太久远了，我可能记错了吧



***@***.***
 
发件人： Yaoyu
发送时间： 2023-07-24 20:50
收件人： prometheusXN/LADAN
抄送： prometheusXN; Comment
主题： Re: [prometheusXN/LADAN] 数据预处理问题 (Issue #14)
10case per label？？不是过滤掉低于100次频率的法条和罪名吗？

**Comment by prometheusXN** [comment]
为啥还要重新划分啊，直接用的比赛划分好的数据集跑的实验



***@***.***
 
发件人： Yaoyu
发送时间： 2023-07-24 20:57
收件人： prometheusXN/LADAN
抄送： prometheusXN; Comment
主题： Re: [prometheusXN/LADAN] 数据预处理问题 (Issue #14)
对了 还有一个问题，在过滤掉指定的一些低频数据之后，没有必要再划分数据集吗？还是出于哪些考虑呢？希望得到您的回答

**Comment by prometheusXN** [comment]
当然，你把所有的数据放在一起之后在重新划分数据也是可以的，我们这里主要是和其他baselines的实验设置保持一致。


***@***.***
 
发件人： Yaoyu
发送时间： 2023-07-24 20:57
收件人： prometheusXN/LADAN
抄送： prometheusXN; Comment
主题： Re: [prometheusXN/LADAN] 数据预处理问题 (Issue #14)
对了 还有一个问题，在过滤掉指定的一些低频数据之后，没有必要再划分数据集吗？还是出于哪些考虑呢？希望得到您的回答
―

**Comment by Yyy11181** [comment]
你好 感谢您的悉心解答 ！
之前您说“最好是对于训练集进行统计的，否则你的模型很可能面临few-shot或者zero-shot 的问题”，能举个例子吗？不懂

**Comment by prometheusXN** [comment]
你如果把测试集也加入统计的话，那不是实际训练的时候，有一些类别样本数量就不足100了么？设想比较极端的情况，那么你训练集里面有可能有一些类别的训练样本特别少，甚至是没有。



***@***.***
 
发件人： Yaoyu
发送时间： 2023-08-05 23:07
收件人： prometheusXN/LADAN
抄送： prometheusXN; Comment
主题： Re: [prometheusXN/LADAN] 数据预处理问题 (Issue #14)
你好 感谢您的悉心解答 ！
之前您说“最好是对于训练集进行统计的，否则你的模型很可能面临few-shot或者zero-shot 的问题”，能举个例子吗？不懂

**Comment by Yyy11181** [comment]
好的 明白了 谢谢你！祝学业顺利！

**Comment by lamaxiyasit** [comment]
@Yyy11181 请问 这个模型 你已经跑通了吗
