### ISSUE TITLE
When will the dual anonymity period end?

### ISSUE THREAD

**Issue by ljkfd3** [prometheusXN/LADAN#3]

**Comment by prometheusXN** [comment]
I don't understand exactly what you mean

**Comment by ljkfd3** [comment]
![捕获](https://user-images.githubusercontent.com/42198090/82894804-c272ed80-9f85-11ea-81d8-778943c39a26.PNG)

**Comment by prometheusXN** [comment]
sorry, this is a description of the code we provide in dropbox during the review phase. I forgot to delete it when I copied it. The double-blind phase has already been over.

**Comment by ljkfd3** [comment]
I can not run 'data_and_config/data/tongji3.py’， because there are not "law.txt" and "accu.txt" file

**Comment by ljkfd3** [comment]
Thanks
