### ISSUE TITLE
The problem about the Number of Law Articles and Charges

### ISSUE THREAD

**Issue by KennardXiong** [prometheusXN/LADAN#6]
Hi, I am interested in you work and have tried to reproduce the results on the **CAIL-small** dataset. But I encounter some problems when I perform **the preprocessing on the dataset.**

The first problem is about the file **law.txt** and the file **accu.txt** in the script **tongji_3.py**. I do not see those two files in you git repository LADAN, but  I find two files named law.txt and accu.txt in the git repository https://github.com/china-ai-law-challenge/CAIL2018/tree/master/baseline . I have tried to run the script **tongji_3.py** with these two files on the CAIL-small dataset, but it reports an **error** that some accusations in the **data_train.json/ data_test.json/ data_valid.json of CAIL-small** are not included in the **accu.txt**. Meanwhile, I notice that **the law number and the accusation number** in the above **law.txt** and **accu.txt** are **183** and **202**, which can not match the statistical info on both CAIL-small and CAIL-big (and I also think it should not match) in your paper **Distinguish Confusing Law Articles for Legal Judgment Prediction**. I really wanna figure out whether my method of generating these files is right or not?

Based on the first problem, I try to traverse all samples in all three files of CAIL-small and record all the accusations and law articles that appear at least once in **my own accu.txt and law.txt.** There are 202 accusations and 183 law articles in these two files respectively. I try to use these two files to run the script **tongji_3.py**, the error mentioned in the first problem is gone, and it generates two files new_law.txt and new_accu.txt by filtering out law articles and accusations that appear less than 100 times (according to the paper). But **the number of my new_law.txt is 101 and the number of my new_accu.txt is 117**, which are both a little bit less than the number of **law articles 103 and the number of charges 119 in the paper**. And I also find that the law number in new_law.txt (103)  and the accusation number in new_accu.txt (119) from your repository can precisely match the info you demonstrate in your paper. **So what is the right way to generate the the new_law.txt and the new_accu.txt?**

The third problem is about generating the train_cs.json, the test_cs.json and the valid_cs.json.  I use **my version of  accu.txt, law.txt, new_accu.txt and new_law.txt** to produce **the three *_cs.json files**. But the sample number in all three produced *cs_json files is not equal to the number in the paper. Then I run the **data/make_Legal_basis_data.py** with the three *cs_json files to generate **the final data** that I need to train the model with. It shows that the by processing with the above script, **the final number of training samples and testing samples are 96477 and 24832, which are both less than the training cases number 101619 and the testing cases number 26749 in the paper.**

Really wish that my wordy description does not bother you too much, but I will be extremely grateful that you could point out the  wrong steps in the data preprocessing that lead to the mismatch in the number of training samples, the number of testing samples, the number of the law articles and the number of the accusations. Thanks a lot.

**Comment by CSQianDong** [comment]
+1

**Comment by CSQianDong** [comment]
I got 96540 in train_cs

**Comment by prometheusXN** [comment]
I think it was the different version of the CAIL_small dataset you used that caused the problem.

**Comment by CSQianDong** [comment]
Thank you for your reply. Could you tell me which version is used in your paper? Appreciate for your help~

**Comment by CSQianDong** [comment]
hello？

**Comment by cunyu1943** [comment]
> I got 96540 in train_cs

do you use the new_accu.txt & new_law.txt as the accu.txt & law.txt?
I got the error when I use them
![image](https://user-images.githubusercontent.com/22308895/102177382-65696580-3ede-11eb-92ab-8518f41b4ffb.png)

**Comment by CSQianDong** [comment]
@cunyu1943 no, I use accu.txt & law.txt from [CAIL2018](https://github.com/china-ai-law-challenge/CAIL2018/tree/master/baseline)

**Comment by CSQianDong** [comment]
Maybe this repository's owner could answer our question, If you have time? @prometheusXN

**Comment by cunyu1943** [comment]
> @cunyu1943 no, I use accu.txt & law.txt from [CAIL2018](https://github.com/china-ai-law-challenge/CAIL2018/tree/master/baseline)

but there is still error when I use the file From CAIL2018，could you give a copy of yours？（747731461@qq.com）
and your version of CAIL is newest downloaded from CAIL2018?

**Comment by cunyu1943** [comment]
> @cunyu1943 no, I use accu.txt & law.txt from [CAIL2018](https://github.com/china-ai-law-challenge/CAIL2018/tree/master/baseline)

![image](https://user-images.githubusercontent.com/22308895/102178711-dad63580-3ee0-11eb-90f3-b6e73820ce3b.png)

**Comment by CSQianDong** [comment]
I met the same error. Maybe the code version is not the latest of the owner. I just change `tempaccu` to `tempaccu.replace("[", "").replace("]", "")]`. Then the codes can be run.

**Comment by cunyu1943** [comment]
> tempaccu.replace("[", "").replace("]", "")]

ok,I will have a try, thanks

**Comment by cunyu1943** [comment]
@DQ0408 hello，did you get the result when you finally run train. py? I would appreciate it if you could help me when you are free.

**Comment by CSQianDong** [comment]
@cunyu1943 No, I just run the preprocess pipline. Be free to ask me anything if I can help

**Comment by prometheusXN** [comment]
The data set will be available on a Google cloud disk later. I have been preparing a paper recently, so I am sorry if I did not give timely feedback

**Comment by prometheusXN** [comment]
We have already updated the address of the data file we used, you can download it and try again~
