### ISSUE TITLE
law_label2index_large.pkl not found

### ISSUE THREAD

**Issue by cunyu1943** [prometheusXN/LADAN#9]
when I run LADAN+TopJudge_large.py , the error show that  the file not found under law_processed, it is the same with the law_lable2index.pkl?

![image](https://user-images.githubusercontent.com/22308895/102586768-b333d700-4145-11eb-8f93-f3f38fcdc24a.png)

**Comment by leileigan** [comment]
@cunyu1943 Have you found the law_label2index_large.pkl file?

**Comment by prometheusXN** [comment]
I think you can generate your own law_label2index_large.pkl file to transform the law index to the label index used in your model.

**Comment by prometheusXN** [comment]
I'm sorry I can't find this file myself. Maybe it has been deleted by mistake
